### ISSUE TITLE
run example no result

### ISSUE THREAD

**Issue by luoyanghero** [Valian/docker-python-opencv-ffmpeg#1]
I pull your docker image, run example not results.
My operation as follow:

> [lb@localhost docker-python-opencv-ffmpeg]$ sudo docker run --rm -it -v $PWD:/srv valian/docker-python-opencv-ffmpeg python
> Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
> [GCC 6.2.0 20160914] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cv2; cv2.VideoCapture('/srv/example.mp4').read()
> (False, None)
> >>> 
> 

My env as follow:

> [lb@localhost docker]$ sudo docker info
> [sudo] password for lb: 
> Containers: 14
>  Running: 1
>  Paused: 0
>  Stopped: 13
> Images: 6
> Server Version: 1.13.1
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 28e44a9d8bee5de71147e936fe468eb4e6a0ba1f (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
> runc version: 28e44a9d8bee5de71147e936fe468eb4e6a0ba1f (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
> init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 3.10.0-693.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> Number of Docker Hooks: 3
> CPUs: 4
> Total Memory: 3.57 GiB
> Name: localhost.localdomain
> ID: RAO2:ELLK:XVEH:IQ2T:Y32C:MM3N:24BT:JAZH:GJ4S:CZS6:OHI7:5354
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Registries: docker.io (secure)
> [lb@localhost docker]$ sudo docker images
> REPOSITORY                                     TAG                            IMAGE ID            CREATED             SIZE
> <none>                                         <none>                         99b3bb6d4fd1        13 hours ago        1.84 GB
> docker.io/busybox                              latest                         5b0d59026729        46 hours ago        1.15 MB
> docker.io/nvidia/cuda                          8.0-cudnn5-devel-ubuntu16.04   ad905502078a        8 days ago          1.84 GB
> docker.io/hello-world                          latest                         f2a91732366c        2 months ago        1.85 kB
> docker.io/valian/docker-python-opencv-ffmpeg   latest                         400077365bc8        7 months ago        947 MB
> [lb@localhost docker]$ uname -a
> Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> [lb@localhost docker]$ cat /etc/issue
> \S
> Kernel \r on an \m
> 
> [lb@localhost docker]$ lsb_release -a
> LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
> Distributor ID:	CentOS
> Description:	CentOS Linux release 7.4.1708 (Core) 
> Release:	7.4.1708
> Codename:	Core
> [lb@localhost docker]$ 
>

**Comment by luoyanghero** [comment]
Thanks. I don't put my video into my work folder. Now the output as follow:

> > [lb@localhost docker-python-opencv-ffmpeg]$ sudo docker run --rm -it -v $PWD:/srv valian/docker-python-opencv-ffmpeg python
> [sudo] password for lb: 
> Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
> [GCC 6.2.0 20160914] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cv2; cv2.VideoCapture('/srv/1.rmvb').read()
> [rm @ 0x55afe094d700] Invalid stream index 2 for index at pos 52094568
> (True, array([[[1, 0, 4],
>         [1, 0, 4],
>         [1, 0, 4],
>         ..., 
>         [0, 2, 0],
>         [0, 2, 0],
>         [0, 2, 0]],
> 
>        [[3, 1, 6],
>         [3, 1, 6],
>         [3, 1, 6],
>         ..., 
>         [0, 2, 0],
>         [0, 2, 0],
>         [0, 2, 0]],
> 
>        [[0, 0, 3],
>         [0, 0, 3],
>         [0, 0, 3],
>         ..., 
>         [0, 1, 1],
>         [0, 1, 1],
>         [0, 1, 1]],
> 
>        ..., 
>        [[5, 0, 6],
>         [5, 0, 6],
>         [5, 0, 6],
>         ..., 
>         [0, 0, 0],
>         [0, 0, 0],
>         [0, 0, 0]],
> 
>        [[4, 0, 5],
>         [4, 0, 5],
>         [4, 0, 5],
>         ..., 
>         [0, 1, 0],
>         [0, 3, 0],
>         [0, 3, 0]],
> 
>        [[3, 0, 4],
>         [3, 0, 4],
>         [3, 0, 4],
>         ..., 
>         [0, 2, 0],
>         [0, 4, 0],
>         [0, 4, 0]]], dtype=uint8))
> >>>     
> 
But I don't understand the output meanings.
What does this image can used for?

**Comment by Valian** [comment]
This image just prepares environment with `ffmpeg` and `opencv` installed, and from what I can see in your snippet, it's working properly. Function you've used is documented [here](https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-read). It returns a standard `numpy` array with pixels of the captured image.

I hope this answers your question.
