### ISSUE TITLE
Getting Python Error While STarting Docker Container For Python 

### ISSUE THREAD

**Issue by shivarajnaidu** [Valian/docker-python-opencv-ffmpeg#4]
![image](https://user-images.githubusercontent.com/12374494/46085463-ba1c4b00-c1c3-11e8-8e7c-6ab8ad97423b.png)

**Comment by Valian** [comment]
@shivarajnaidu Thanks for the report! The reason for this error is an invalid default command in Dockerfile.

I'll fix it soon, but a temporary workaround is to just override default command, like this:
`docker run --rm -it valian/docker-python-opencv-ffmpeg:latest python`

**Comment by yuvarajvemula** [comment]
Thank You for quick fix @Valian
