### ISSUE TITLE
FFMPEG with X264 and X265 Support

### ISSUE THREAD

**Issue by leviethung2103** [Valian/docker-python-opencv-ffmpeg#5]
Hi Author,

Thank you for your great work ! I just found the your repo and I am not sure that you are still maintain the code or not. 

I would like to ask you about the FFMPEG with X264 and X265 supports. 

Currently, I've built successfully the Docker image. It works perfectly with X264 codec. However, when I was tried with X265 codec. It said that `OpenCV: FFMPEG: tag 0x35363258/'X265' is not found (format 'matroska / Matroska')'. 

I think I need to rebuild the FFMPEG from source and it failed to make the opencv recognizes ffmpeg I have built. 

Do you have any solutions for my situation ? 

Thank you in advance.

**Comment by arvindrvs** [comment]
Srry, i stopped maintaining it. I just did all these as my college project.

All the best with your work.

**Comment by leviethung2103** [comment]
Thank you for you response. I will close the issue.
